version: '3'

networks:
    laravel:

services:
    nginx:
        build:
            context: .
            dockerfile: nginx.dockerfile
        container_name: webserver
        ports:
            - "8088:80"
        volumes: 
            - ./src:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
        networks:
            - laravel

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        container_name: webapp
        volumes: 
            - ./src:/var/www/html
            - ./db.sqlite:/home/db.sqlite
        ports:
            - "9000:9000"
        networks:
            - laravel

    composer: 
        image: composer:latest
        container_name: composer
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        networks: 
            - laravel

    npm: 
        image: node:14.11
        container_name: npm
        volumes: 
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks: 
            - laravel

    artisan:
        build: 
            context: .
            dockerfile: php.dockerfile
        container_name: artisan
        volumes:
            - ./src:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['/var/www/html/artisan']
        networks: 
            - laravel
